name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history so we can push back to the branch
          fetch-depth: 0 

      - name: Update manifest version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          sudo apt-get update
          sudo apt-get install -y jq

          tmp=$(mktemp)
          jq --arg version "$VERSION" '.version = $version' \
            custom_components/knmi_seismisch/manifest.json > "$tmp"

          mv "$tmp" custom_components/knmi_seismisch/manifest.json

      - name: Commit and push back to repository
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add custom_components/knmi_seismisch/manifest.json
          git commit -m "Bump manifest version to ${GITHUB_REF_NAME#v} [skip ci]" || echo "No changes to commit"
          
          # Explicitly telling Git to push this commit directly to the 'main' branch
          git push origin HEAD:main

      - name: Create ZIP
        run: |
          cd custom_components/knmi_seismisch
          zip -r knmi_seismisch.zip ./

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: custom_components/knmi_seismisch/knmi_seismisch.zip
